language: go

go:
  - 1.14.x
    
install:
- go get honnef.co/go/tools/cmd/staticcheck
- go get -u go.bobheadxi.dev/gobenchdata
- go get -u go.bobheadxi.dev/gobenchdata/x/gobenchdata-web
- go mod download

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...

script:
- make verifiers
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build